# -*- coding: utf-8 -*-
"""
The script processes outputs generated by 'Deff_calculation.py', including Deff distributions, to estimate Spearman and Pearson 
correlation coefficients for the dependency of parameters on fluorescent intensity, which is separately collected using Fiji, 
number of detected particles and so on... across cell population.

"""

import csv 
import matplotlib.pyplot as plt
from matplotlib import cm
import numpy as np
from scipy.stats import pearsonr, spearmanr
import pandas as pd
import os
from scipy.stats import gaussian_kde
from scipy.integrate import simps


directory = 'ARTICLE_V3_r6cf0p1_l1d5_R20.9_10trlength_5Derr_5aerr_lagtime5.0ms_nw0.00072T308 DYNAMIC AND STATIC ERROR'
save =  False
Deff_filter = False
Intenisities_file = 'Intenisties.csv'

ExperDirectory = 'D:082124_082524/'
experiments = [f for f in os.listdir(ExperDirectory) if os.path.isdir(os.path.join(ExperDirectory, f))]
experiments = [['0.24ugml doxycycline 4pm 35oC', '0.24 ugml doxycycline 5pm repeat 2'], ['0.24ugml doxycycline 12_30pm  2d 35oC', '0.24 ugml doxycycline 11am 2day repeat 2'], ['0.5ugml doxycycline 6pm 35oC', '0.5ugml doxycycline 12am repeat2 35oC'], ['0.5ugml doxycycline 2pm 2d 35oC','0.5ugml doxycycline 19_30m day2 repeat2 35oC'], ['1ugml doxycycline 7_20pm 35oC', '1ugml doxycycline 10_30am repeat2 35oC'], ['1ugml doxycycline 3pm 2d 35oC', '1ugml doxycycline 8_30am 2day repeat2 35oC']]



# Set Times New Roman and font sizes globally
plt.rcParams['figure.figsize'] = [16, 14]  # Adjust based on your needs
plt.rcParams.update({
    'font.family': 'Times New Roman', 
    'font.weight': 'bold', 
    'axes.labelweight': 'bold', 
    'axes.titleweight': 'bold', 
    'legend.fontsize': 40,
    'xtick.labelsize': 40,  
    'ytick.labelsize': 40,
})


def Boxplot_And_Statistics(x_values, distributions, x_label = None, y_label = None, save_name = None, x_limit = None, y_limit = None, xsticks_division = 50):
    means = [np.mean(group) for group in distributions]
    std_dev = [np.std(group, ddof = 1) for group in distributions]
    medians = [np.median(group) for group in distributions]
    
    
    #Do std dev another color or alpha!
    plt.figure()
    plt.errorbar(x_values, means, yerr = std_dev, fmt='o', color = 'blue', label = 'mean',ecolor = 'blue', alpha = 0.3)
    plt.errorbar(x_values, medians, fmt='o', color = 'magenta', label= 'median', alpha = 0.3)
    plt.xlabel(f'{x_label}')
    plt.ylabel(f'mean of {y_label}')
    plt.ylim(y_limit)
    if 'Int' in save_name:
        plt.axvline(x=123-80, color='red', linestyle='--', linewidth=2)
    plt.legend()
    if save:
        plt.savefig(f'{parent_dir}{directory}/ARTICLE_V3_powerlaw_{save_name}_{experiment[0]} scaled.pdf', dpi=300)
    plt.show()
    
    plt.figure()
    plt.errorbar(std_dev, means, fmt='o')
    plt.xlabel(f'standard deviation of {y_label}')
    plt.ylabel(f'mean of {y_label}')
    plt.show()
    

    # Create the plot
    fig, ax = plt.subplots(figsize=(18, 14))
    # Plot boxplots at the positions specified by x_values
    for i, (x, y) in enumerate(zip(x_values, distributions)):
        bp = ax.boxplot(y, positions=[x], widths=3, patch_artist=True)  # You can adjust widths as needed
        # Set transparency for each component
        for box in bp['boxes']:
            box.set(facecolor='white', alpha=0.5)  # Adjust 'alpha' as needed for transparency
        for whisker in bp['whiskers']:
            whisker.set(color='black', alpha=0)
        for cap in bp['caps']:
            cap.set(color='black', alpha=0)
        for median in bp['medians']:
            median.set(color='darkred', alpha=1, linewidth=3)
        for flier in bp['fliers']:
            flier.set(marker='o', color='red', alpha=0)

    # Adjust the axis
    #ax.set_xticks(np.arange(min(Int_sorted), max(Deff_boxplot_sorted) + 1, 0.5))  # Adjust tick frequency
    # Adjust the x-axis to include all ticks, including the last one
    # tick_positions = x_values[::50]  # Show every 5th tick
    # if x_values[-1] not in tick_positions:
    #     tick_positions = np.append(tick_positions, x_values[-1])
    
    tick_positions = np.arange(0, max(x_values) + 1, xsticks_division)  # Create ticks every 50 units
    ax.set_xticks(tick_positions)  # Set the tick positions
    ax.set_xticklabels(tick_positions, ha='right')  # Set the tick labels
    ax.set_xlabel(x_label, fontweight = 'bold', fontsize = 40)
    ax.set_ylabel(y_label, fontsize = 40)
    
    # Customize the appearance of the ticks (line length, width, direction, etc.)
    ax.tick_params(axis='x', which='both', length=10, width=2, direction='out', top=True)  # X-axis ticks
    ax.tick_params(axis='y', which='both', length=10, width=2, direction='out', right=True)  # Y-axis ticks

    
    ax.set_xlim(x_limit)  # Set x-axis limits
    ax.set_ylim(y_limit)  # Set y-axis limits
    
    if 'Int' in save_name:
        plt.axvline(x=123-80, color='red', linestyle='--', linewidth=2)
    
    if save:
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure2_{save_name}_{experiment[0]}.png', dpi=300)
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure2_{save_name}_{experiment[0]}.pdf', dpi=300)

    plt.show()

    # Statistics

    # Spearman correlation (monotonic relationship)
    spearman_corr, spearman_p = spearmanr(x_values, medians)
    print(f"Spearman correlation: {spearman_corr}, p-value: {spearman_p}")

    # Pearson correlation (linear relationship)
    pearson_corr, pearson_p = pearsonr(x_values, medians)
    print(f"Pearson correlation: {pearson_corr}, p-value: {pearson_p}")
    
     #Create a DataFrame with the results
    results = {
        'Experiment': [experiment, experiment],
        'Statistic': ['Spearman Correlation', 'Pearson Correlation'],
        'Value': [spearman_corr, pearson_corr],
        'p-value': [spearman_p, pearson_p]
        }
    
    df = pd.DataFrame(results)
    
    # Save the DataFrame to an Excel file
    if save:
        output_file = rf'D:\article_GEM_U2OS_expression\Main Revision\Figure2_{save_name}.csv'
        
        # Check if the file exists to avoid writing the header multiple times
        try:
            # Append to the file and avoid writing header if the file already exists
            df.to_csv(output_file, mode='a', header=not os.path.exists(output_file), index=False)
        except Exception as e:
            print(f"An error occurred while saving: {e}")
        else:
            print(f"Results for {experiment} have been saved to {output_file}")
            

def PDF_KDE(data, kde_min_filter, kde_max_filter, Value = 'Value'):
    
    plt.hist(data)
    plt.show()
    
    # Kernel density estimation
    kde = gaussian_kde(data) #PDF? 
    
    # Define the range for the PDF
    x_vals = np.linspace(kde_min_filter,  kde_max_filter, 500)  # Generate 500 points over the range
    pdf_vals = kde(x_vals)  # Evaluate the PDF
    
    
    # Check if the integral of the PDF equals 1
    integral = simps(pdf_vals, x_vals)  # Numerical integration
    print(f"Integral of the KDE PDF: {integral:.6f} (should be close to 1)")
    
    # Plot the result
    plt.plot(x_vals, pdf_vals, label="KDE PDF")
    plt.xlabel(Value)
    plt.ylabel("Probability density")
    plt.title("Probability Density Function")
    plt.legend()
    plt.show()
    
    return x_vals, pdf_vals

for experiment in experiments: 
    print(f'{experiment}')
    
    Deff_AllCells = []
    Deff_sigma_AllCells= []
    Delta_AllCells = []
    Alpha_AllCells = []
    Da_AllCells = []
    
    Deff_boxplot = []
    Delta_boxplot = []
    Alpha_boxplot = []
    Trajectory_length_boxplot = []
    Files_count_Deff = [] #to check data from Data_after_tracking and Intensities
    
    Int_experiment = []
    Particles_experiment = []
    
    #extract intensities and prepare data
    # Load the CSV file
    
    for repeat in experiment: 
            
        parent_dir = f'{ExperDirectory}{repeat}/'
        files = [f for f in os.listdir(parent_dir) if os.path.isdir(os.path.join(parent_dir, f))]
        
        data = pd.read_csv(f'{parent_dir}{Intenisities_file}')  # Use delimiter for space or tab
        
        # Manually assign column names
        data.columns = ['file', 'Area', 'Mean', 'StdDev', 'IntDen', 'RawIntDen']
        
        # Ensure your CSV has 'x' and 'y' columns
        Files_count_Intensities = data['file']
        Int = data['Mean']
        Int_sigma = data['StdDev']
        
        Files_count_Intensities = list(Files_count_Intensities)
        Int = list(Int)
        Int_sigma = list(Int_sigma)
        

        Int = [round(x-80,0) for x in Int]
        
        for file_index, file in enumerate(files): 
            
            if not os.path.exists(f'{parent_dir}{file}/r6cf0p1_l1d5/'):
                continue
            
            if not os.path.exists(f'{parent_dir}{directory}/Data_after_tracking_{file}.csv'):
                continue
            
            
            Diffusion = []
            Delta = []
            Alpha = []
            Diffusion_error = []
            check = False 
            Trajectory_length = [] 
            
            detected_particles = 0
            #Convertation of converted_data to the list ['trajectory №', [time_o], [x], [y], [time_frame]] for plotting
            # Open the CSV file
            with open(f'{parent_dir}{file}/frames_sec.csv', newline='') as data:
                reader = csv.reader(data)
                # Skip the header if there is one
                next(reader, None)
                
                # Get the first column values
                first_column = [row[0] for row in reader]
            frames = len(first_column) 
            
            
            with open(f'{parent_dir}{directory}/Data_after_tracking_{file}.csv') as data:
                data_file = csv.reader(data, delimiter=',')
                            
                # Создание градиента цветов от красного до синего
                norm = plt.Normalize(vmin=0, vmax=0.05)
                #norm = plt.Normalize(vmin=0.8, vmax=np.pi/2)
                cmap = cm.get_cmap('plasma')
        
                # Построение графика
                fig, ax = plt.subplots()
                
                traj_count = 0
                for row in data_file:
                    
                    if 'Trajectory' in row[0]:
                        if check == True:
                            #space to plot
                            ax.plot(x, y, color=cmap(norm(float(stripped_list[1]))))
                            Trajectory_length.append(t[-1]*1000)
                            
                        # Split the string by commas
                        split_string = row[0].split(',')
                        # Strip whitespace from each element
                        stripped_list = [element.strip() for element in split_string]
                        #print(stripped_list)
                        
                        if Deff_filter == True: 
                            if float(stripped_list[1]) > 0.02:
                                Diffusion.append(float(stripped_list[1]))
                                Diffusion_error.append(float(stripped_list[2]))
                                Delta.append(float(stripped_list[4]))
                                Alpha.append(float(stripped_list[10]))
                            
                                Deff_AllCells.append(float(stripped_list[1]))
                                Deff_sigma_AllCells.append(float(stripped_list[2]))
                                Delta_AllCells.append(float(stripped_list[4]))
                                Alpha_AllCells.append(float(stripped_list[10]))
                                Da_AllCells.append(float(stripped_list[7]))
                                
                                detected_particles += 1
                                
                        if Deff_filter != True: 
                                Diffusion.append(float(stripped_list[1]))
                                Diffusion_error.append(float(stripped_list[2]))
                                Delta.append(float(stripped_list[4]))
                                Alpha.append(float(stripped_list[10]))
                            
                                Deff_AllCells.append(float(stripped_list[1]))
                                Deff_sigma_AllCells.append(float(stripped_list[2]))
                                Delta_AllCells.append(float(stripped_list[4]))
                                Alpha_AllCells.append(float(stripped_list[10]))
                                Da_AllCells.append(float(stripped_list[7]))
                                
                                detected_particles += 1
                        
                        t = []
                        x = []
                        y = []
                        
                        check = True
                        
                    if len(row)==3 and 'time' not in row:
                        t.append(float(row[0]))
                        x.append(float(row[1]))
                        y.append(float(row[2]))
                
            ax.plot(x, y, color=cmap(norm(float(stripped_list[1]))))
            Trajectory_length.append(t[-1]*1000)
            
            
            #color trajectorymap according to alpha parameter
            # Добавление цветовой шкалы сбоку
            sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
            sm.set_array([])
            cbar = plt.colorbar(sm, ax=ax, orientation='vertical')
            cbar.set_label('Deff')
            
            plt.xlabel('X')
            plt.ylabel('Y')
            #plt.title(f'Trajectories colored by a ({file})')
            plt.title('Trajectories colored by Deff, power-law fit')
            
            
            if False:
                plt.savefig(f'{parent_dir}{directory}/DiffusionMap_{file}_{experiment[0]}.pdf', dpi=300)
            plt.show()
            
            if not Diffusion:
                print(f'no tracks, {file}')
            else:
                Int_experiment.append(Int[file_index])
                print(file, Int[file_index], Files_count_Intensities[file_index])
            
                Diffusion = np.array(Diffusion)
                Delta = np.array(Delta)
                Alpha = np.array(Alpha)
                Diffusion_error = np.array(Diffusion_error)
                Trajectory_length = np.array(Trajectory_length)
                Deff_boxplot.append(Diffusion)
                Delta_boxplot.append(Delta)
                Alpha_boxplot.append(Alpha)
                Trajectory_length_boxplot.append(Trajectory_length)
                
                Particles_experiment.append(detected_particles/frames*100)
        
    Deff_AllCells = np.array(Deff_AllCells)
    Deff_sigma_AllCells= np.array(Deff_sigma_AllCells)
    Delta_AllCells=np.array(Delta_AllCells)
    Alpha_AllCells=np.array(Alpha_AllCells)
    
    #for distribution in Deff_boxplot:
                
    #    pdf_Deff_cell = PDF(distribution)
    #    plt.figure()
    #    plt.plot(pdf_Deff_cell[0], pdf_Deff_cell[1], label='PDF')
    #    plt.xlim(0,0.05)
    #    plt.ylim(0,80)
    #    plt.xticks()
    #    plt.yticks()
    #    plt.xlabel(f'Deff values by cell')
    #    plt.ylabel('Probability Density')
    #    plt.title('Histogram and PDF of Deff')
        
    #plt.show()
    
    #pdf_Deff = PDF(Deff_AllCells, 30)
    pdf_Deff = PDF_KDE(Deff_AllCells, 0, 0.06)
    # Plot the results
    
    Deff_median = np.median(Deff_AllCells)
    Deff_mean = np.mean(Deff_AllCells)
    Deff_mean_sigma = np.std(Deff_AllCells, ddof=1)

    plt.figure()
    plt.hist(Deff_AllCells, bins=30, density=True, alpha=0.5, label='Histogram (normalized)', color = 'lightblue')
    plt.plot(pdf_Deff[0], pdf_Deff[1], label='PDF', color='green', linewidth = 4)
    plt.ylim(0,90)
    plt.xticks()
    plt.yticks()
    plt.text(0.03, 60, f'mean = {Deff_mean:.3f} ± {Deff_mean_sigma:.3f} \nmedian = {Deff_median:.3f}', fontsize=50, color='black', ha='left', va='center')
    plt.xlabel('$D_{eff}$ values', fontsize = 50)
    plt.ylabel('Probability Density', fontsize = 50)
    #plt.title(r'Histogram and PDF of $D_{eff}$', fontsize = 50)
    plt.legend()
    if save == True:
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure1C_{experiment[0]}.png', dpi=300)
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure1C_{experiment[0]}.pdf', dpi=300)
    plt.show()
    
    
    pdf_Alpha = PDF_KDE(Alpha_AllCells, 0, 2)
    
    # Plot the results
    
    Alpha_median = np.median(Alpha_AllCells)
    Alpha_mean = np.mean(Alpha_AllCells)
    Alpha_mean_sigma = np.std(Alpha_AllCells, ddof=1)

    plt.figure()
    plt.hist(Alpha_AllCells, bins=30, density=True, alpha=0.5, label='Histogram (normalized)', color = 'lightblue')
    plt.plot(pdf_Alpha[0], pdf_Alpha[1], label='PDF', color='green', linewidth = 4)
    plt.xticks()
    plt.ylim(0,2)
    plt.yticks()
    plt.text(1.1, 1.3, f'mean = {Alpha_mean:.1f} ± {Alpha_mean_sigma:.1f} \nmedian = {Alpha_median:.1f}', fontsize=50, color='black', ha='left', va='center')
    plt.xlabel('α values', fontsize = 50)
    plt.ylabel('Probability Density', fontsize = 50)
    #plt.title('Histogram and PDF of α', fontsize = 50)
    plt.legend()
    if save == True:
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure1D_{experiment[0]}.png', dpi=300)
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure1D_{experiment[0]}.pdf', dpi=300)
    plt.show()
    
    pdf_Da = PDF_KDE(Da_AllCells, 0, 4)
    
    # Plot the results
    
    Da_median = np.median(Da_AllCells)
    Da_mean = np.mean(Da_AllCells)
    Da_mean_sigma = np.std(Da_AllCells, ddof=1)

    plt.figure()
    plt.hist(Da_AllCells, bins=30, density=True, alpha=0.5, label='Histogram (normalized)', color = 'lightblue')
    plt.plot(pdf_Da[0], pdf_Da[1], label='PDF', color='green', linewidth = 4)
    plt.xticks()
    plt.yticks()
    plt.text(1, 1.5, f'mean = {Da_mean:.2f} ± {Da_mean_sigma:.2f} $\mu$m$^2$/$sec^α$ \nmedian = {Da_median:.2f} $\mu$m$^2$/$sec^α$', fontsize=50, color='black', ha='left', va='center')
    plt.xlabel('$D_{α}$ values, $\mu$m$^2$/$sec^α$', fontsize = 50)
    plt.ylabel('Probability Density', fontsize = 50)
    #plt.title(r'Histogram and PDF of $D_{α}$', fontsize = 50)
    plt.legend()
    if save == True:
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure1E_{experiment[0]}.png', dpi=300)
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure1E_{experiment[0]}.pdf', dpi=300)
    plt.show()
    
    #DEFF VIOLIN PLOT
    
    # Set up the figure and axis
    #fig, ax = plt.subplots(figsize=(18, 10))
    
    # Plotting distributions as violin plots
    #sns.violinplot(data=Deff_boxplot, ax=ax)
    
    # Adjust the axis
    #ax.set_xticks(range(len(list(Int_experiment))))
    #ax.set_xticklabels(Int_experiment)
    #ax.set_xlabel('X values')
    #ax.set_ylabel('Y values')
    #ax.set_title('Plot with Distributions at Each Data Point')
    #plt.xticks(fontsize=20,rotation=90, ha='right')
    #plt.xticks(rotation=90, ha='right')
    #plt.yticks(fontsize=20)
    #if save == True:
    #    plt.savefig(f'{parent_dir}{directory}/Deff violin plot_DeffFilter{Deff_filter}.pdf', dpi=300)
    #plt.show
    #plt.show()       
        
    
    Boxplot_And_Statistics(Int_experiment, Deff_boxplot, 'Mean Fluorescent Intensity of Sapphire', r'$D_{eff}$', 'Deff_Int',  x_limit = [0, 300], y_limit = [0.01, 0.035])
    Boxplot_And_Statistics(Int_experiment, Alpha_boxplot, 'Mean Fluorescent Intensity of Sapphire', 'a' ,'a_Int',  x_limit = [0,300], y_limit = [0.4, 1.4])
   
    Boxplot_And_Statistics(Particles_experiment, Deff_boxplot, 'Number of detected tracks per 100 frames', r'$D_{eff}$', 'Deff_particles',  x_limit = [0, 120], y_limit = [0.01, 0.035], xsticks_division = 20)
    Boxplot_And_Statistics(Particles_experiment, Alpha_boxplot, 'Number of detected tracks per 100 frames', 'a' ,'a_particles',  x_limit = [0,120], y_limit = [0.4, 1.4], xsticks_division = 20)
   
    plt.figure()
    plt.plot(Int_experiment, Particles_experiment, marker='o', linestyle='None')  # This will plot just points, no line
    plt.xlabel('Mean Fluorescent Intensity of Cell', fontsize = 40)
    plt.ylabel('Number of detected tracks per 100 frames', fontsize = 40)
    plt.axvline(x=123-80, color='red', linestyle='--', linewidth=2)
    if save:
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure2_S_{experiment[0]}.pdf', dpi=300)
        plt.savefig(rf'D:\article_GEM_U2OS_expression\Main Revision\pictures\Figure2_S_{experiment[0]}.png', dpi=300)
    plt.show()
    
    particles_LE = []
    particles_HE = []
    for Int, particle in zip(Int_experiment, Particles_experiment):
        if Int < 123-80: 
            particles_LE.append(particle)
        else:
            particles_HE.append(particle)
            
    plt.figure()
    plt.hist(particles_LE, label = 'LE')
    plt.hist(particles_HE, label = 'HE')
    plt.legend()
        
    
 #    Boxplot_And_Statistics(Int_experiment, Delta_boxplot, 'Fluorescent Intensity', 'phase angle', 'phase angle', x_limit = [0,300], y_limit = [0, np.pi/2*1.5])
 #    Boxplot_And_Statistics(Int_experiment, Trajectory_length_boxplot, 'Fluorescent Intensity', 'Trajector_length ms' ,'Trajectories_length',  x_limit = [0,300], y_limit = [50, 400])
           
    
